from tactic 4.0.1.v04 when trying to save/update a template project an exception is thrown:
SObjectValueException: Column [project_type_code] does not exist in search_object type [sthpw/project]

the "code" column in sthpw/project is expected to be named "project_type_code" because of the sobject_code relation between sthpw/project and sthpw/project_type.
expliciting the from_col in src/pyasm/biz/schema.py solve the problem...