Patch for src/pyasm/biz/expression.py bug fetching wrong SObjects in many to many handling
    Affected versions: 4.1.0v03, 4.1.0v04 are the ones I tested

    How to reproduce:
    To be sure there were no site or project specific interferences I dowloaded the 4.1.0.v03 VMware Image from http://community.southpawtech.com/downloads and used the VFX project.
    The easiest way to show the bug is using the Shot planner. Connect to Tactic and open the VFX project, in the sidebar click on "Tools"->"Shot Planner", see the assets and shots section loading into the shot planner tab. Click on "Tools"->Shot Planner" again and keep cliking, at some point, usually after 3 to 5 reloads you'll see a duplicated asset for a specific shot into the "Asset Drop" column. The bug appears randomly every 2 to 5 reloads but gets much worse when the shots and assets number gets higher. Note that the duplicated asset is really referring to another asset, on a shot having "camera001, set001, vehicle001" but showing "camera001, camera001, vehicle001" in the Asset drop if you "click to remove" on the second camera001 it will remove set001

    P.S.
        This was quite a long debug session, took me many hours to follow the flow of tactic code in the pyasm namespace. Tactic's code is huge and I'm not sure I understand all of the implications for this patch.

Patch for src/tactic/ui/table/drop_element_wdg.py bug fetching wrong SObjects in many to many handling

Affected versions: 4.1.0v03, 4.1.0v04 are the ones I tested

How to reproduce:
To be sure there were no site or project specific interferences I dowloaded the 4.1.0.v03 VMware Image from http://community.southpawtech.com/downloads and used the VFX project.
The easiest way to show the bug is using the Shot planner. Connect to Tactic and open the VFX project, in the sidebar click on "Tools"->"Shot Planner", see the assets and shots section loading into the shot planner tab. Click on "Tools"->Shot Planner" again and keep cliking, at some point, usually after 3 to 5 reloads you'll see a duplicated asset for a specific shot into the "Asset Drop" column. The bug appears randomly every 2 to 5 reloads but gets much worse when the shots and assets number gets higher. Note that the duplicated asset is really referring to another asset, on a shot having "camera001, set001, vehicle001" but showing "camera001, camera001, vehicle001" in the Asset drop if you "click to remove" on the second camera001 it will remove set001

As oboreo suggested I'm moving the clear_cache() call from src/pyasm/biz/expression.py to src/tactic/ui/table/drop_element_wdg.py

from tactic 4.0.1.v04 when trying to save/update a template project an exception is thrown:

SObjectValueException: Column [project_type_code] does not exist in search_object type [sthpw/project]

the "code" column in sthpw/project is expected to be named "project_type_code" because of the sobject_code relation between sthpw/project and sthpw/project_type.
expliciting the from_col in src/pyasm/biz/schema.py solve the problem...